all:	crea	bin/1	bin/2	bin/3	bin/4	bin/5	bin/6	bin/7	bin/8	bin/9	bin/10

bin/1:	src/1.cpp
	g++ src/1.cpp -o bin/1

bin/2:	src/2.cpp
	g++ src/2.cpp -o bin/2


bin/3:	src/3.cpp
	g++ src/3.cpp -o bin/3

bin/4:	src/4.cpp
	g++ src/4.cpp -o bin/4

bin/5:	src/5.cpp
	g++ src/5.cpp -o bin/5

bin/6:	src/6.cpp
	g++ src/6.cpp -o bin/6

bin/7:	src/7.cpp
	g++ src/7.cpp -o bin/7

bin/8:	src/8.cpp
	g++ src/8.cpp -o bin/8

bin/9:	src/9.cpp
	g++ src/9.cpp -o bin/9

bin/10:	src/10.cpp
	g++ src/10.cpp -o bin/10

crea:
	@mkdir -p bin obj lib

clean:
	@$(RM) bin/*