all:	bin/1	bin/2	bin/3	bin/4

bin/1:	src/1.cpp
	g++ src/1.cpp -o bin/1

bin/2:	src/2.cpp
	g++ src/2.cpp -o bin/2


bin/3:	src/3.cpp
	g++ src/3.cpp -o bin/3

bin/4:	src/4.cpp
	g++ src/4.cpp -o bin/4


clean:
	rm bin/*